### ISSUE TITLE
Need to escape single quotes

### ISSUE THREAD

**Issue by bstanley0811** [jansanchez/gulp-email#1]
I found that if the content of my email has any single quotes, the email fails to send.  This happens quite often with inline css and fonts. (ie. font-family: 'Open Sans'; ).  Adding the following to line 102 in gulp-email.js fixed this for me.:

```
content = content.replace(/'/g, "\\'");
```

Making the condition look like this:

```
if (haveTextHtml === false) {
    args.push('--form-string');
    content = content.replace(/'/g, "\\'");
    args.push('html=\'' + content +'\'');
}
```

**Comment by ryanburgess** [comment]
Was @bstanley0811's fix implemented? This issue still seems to be happening.

**Comment by jansanchez** [comment]
Hi @ryanburgess, what's the html code that fails? to help you.
