### ISSUE TITLE
Breaks if there are single quotes in the email

### ISSUE THREAD

**Issue by jamieholliday** [jansanchez/gulp-email#3]
I am getting syntax errors in console when there are any single quotes in the html file. For example if there are inlined styles like this:

```
<body style="font-family: 'Helvetica','Arial','sans-serif';">
```

**Comment by jansanchez** [comment]
Hi Jamie, please can you paste the content of the .html file?
Thanks.

**Comment by jamieholliday** [comment]
Here is a reduced version that I was still getting an error with:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Test Email</title>
  </head>
  <body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" yahoo="fix" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background: #ebebeb; color: #6C6C6C; font-family: 'Helvetica','Arial','sans-serif'; font-size: 12px;" bgcolor="#ebebeb">
    <table><tr><td>test's</td></tr></table>
  </body>
</html>

**Comment by jansanchez** [comment]
Perfect, Now we do the tests.

**Comment by jamieholliday** [comment]
I have done a few more tests and it looks to me like curl has the problem with escaping the \'

**Comment by jansanchez** [comment]
Yes, @jamieholliday the problem is curl, already I have a solution but I will have that I do it.

**Comment by jansanchez** [comment]
@jamieholliday, The solution is create a temp file with the html content and send the email without problems

```
-F attachment=@temp/message.html
```
